name: FerdiP
description: Embedded Systems Engineering
avatar: >-
  https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  email: ferdinand.phan.ee@gmail.com
  github: FerdiP
  linkedin: 'https://www.linkedin.com/in/duc-duy-phan-8b4087111/'
  stackoverflow: null
disqus: null
google_analytics: null
url: null
baseurl: ''
permalink: '/:title/'
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: ':expanded'
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-admin
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
